---

- name: SHOW VERSION
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run the command 'show version'
      ios_command:
        commands: show version
      register: output1

    - name: print result
      debug:
        var: output1.stdout_lines
    
    - name: Show all interfaces
      ios_command:
        commands: sh ip int brief
      register: output1
      
    - name: print result
      debug:
        var: output1.stdout_lines